combined_county_data <- read_csv(here("data/combined_county_data.csv"), guess_max = 100000)
combined_county_wide <- read_csv(here("data/combined_county_data_wide.csv"))
case_table <- read_csv(here("data/cases_sample_date.csv"))
reinfections <- read_csv(here("data/reinfections.csv"))
tests_table <- read_csv(here("data/tests_table.csv"), guess_max = 100000)
deaths <- read_csv(here("data/death_date_table.csv"), guess_max = 100000)
hospitals <- read_csv(here("data/hospitalizations.csv"))
age_table <- read_csv(here("data/demographics/age_table.csv"))
race_table <- read_csv(here("data/demographics/race_table.csv"), guess_max = 100000)
race_table_processed <- race_table %>%
	mutate(lag_date = date - 7) %>%
	left_join(x = .,
			  y = {.} %>% select(date, race, lag_cases = cases),
			  by = c("lag_date" = "date", "race")) %>%
	mutate(new_cases_percap_7day = ((cases - lag_cases) / 7) / (pop / 100000)) %>%
	filter(!is.na(new_cases_percap_7day))
raw_hospital_data <- read_csv(here("data/raw_hospital_data.csv"))
clean_hosp_capacity <- read_csv(here("data/hospital_capacity.csv"))
breakthroughs <- read_csv(here("data/breakthroughs", "breakthroughs.csv"))
breakthroughs_weighted <- read_csv(here("data/breakthroughs", "breakthroughs-weighted.csv"))
breakthroughs_weighted_age <- read_csv(here("data/breakthroughs", "breakthroughs-weighted-age.csv"))
vaccine_doses <- read_csv(here("data/vaccine-data/total-doses.csv"))
vaccine_age <- read_csv(here("data/vaccine-data/vaccine_age.csv"))
vaccine_gender <- read_csv(here("data/vaccine-data/vaccine_gender.csv"))
vaccine_providers <- read_csv(here("data/vaccine-data/vaccine_provider.csv"))
vaccine_1x_county <- read_csv(here("data/vaccine-data/vaccine-1dose-county.csv"))
vaccine_1x_age <- read_csv(here("data/vaccine-data/vaccine-1dose-age.csv"))
vaccine_1x_gender <- read_csv(here("data/vaccine-data/vaccine-1dose-gender.csv"))
doses_shipped <- read_csv(here("data/vaccine-data/doses-shipped.csv"))
vaccine_1x_age_county <- read_csv(here("data/vaccine-data/vaccine-1dose-age-county.csv"))
vaccine_race <- read_csv(here("data/vaccine-data/vaccine-race.csv"))
vaccine_race_progress <- read_csv(here("data/vaccine-data/vaccine-race-progress.csv"))
vaccine_zip <- read_csv(here("data/vaccine-data/vaccine-zip.csv"), col_types = cols(zip = col_character()))
source(here("R/load-data/download-wastewater.R"))
covid_totals_report <-  read_csv(here("data/covid_totals_report.csv"))
covid_data_report <- read_csv(here("data/covid_data_report.csv"))
covid_trends_report <- read_csv(here("data/covid_trends_report.csv"))
covid_data_actual <- read_csv(here("data/covid_data_actual.csv"))
covid_trends_actual <- read_csv(here("data/covid_trends_actual.csv"))
cdc <- read_csv(paste0("https://data.cdc.gov/resource/unsk-b7fc.csv?$$app_token=", cdc_token, "&location=MN"))
county_map <- read_sf(here("shapefiles/mn_counties/mn_counties.shp"))
zip_map <- read_sf(here("shapefiles/mn_zips/mn_zips.shp"))
current_report_date <- covid_data_report %>% filter(date == max(date)) %>% pull(date)